name: Deploy

# List of secrets that must be defined in GitHub Secrets.
#
# - APP_STORE_CONNECT_ISSUER_ID
# - APP_STORE_CONNECT_KEY_ID
# - APP_STORE_CONNECT_KEY
# - APP_STORE_TEAM_ID
# - MATCH_PASSWORD
# - SSH_PRIVATE_KEY

on:
  workflow_dispatch:
    inputs:
      VERSION_NAME:
        description: "Version Name (e.g. 1.2.3)"
        required: true
        type: string

      BUILD_NUMBER:
        description: "Build Number (e.g. 43)"
        required: true
        type: number

      RELEASE_NOTE:
        description: "Release Note (for automatic review submission)"
        required: false
        default: ""
        type: string

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          # SSH private key used to access your Fastlane match repository.
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 17

      - name: Cmake Cache
        uses: actions/cache@v3
        with:
          path: /usr/local/lib/android/sdk/cmake
          key: cmake-${{ runner.os }}

      - name: Gradle Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: Install Android SDK
        uses: android-actions/setup-android@v3

      - name: Flutter SDK Cache
        uses: actions/cache@v3
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.os }}-flutter-${{ vars.FLUTTER_VERSION }}

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: ${{ vars.FLUTTER_VERSION }}

      - name: Build & Deploy
        uses: MTtankkeo/flutter-fastlane-action@main
        with:
          platform: android
          version-name: ${{ github.event.inputs.VERSION_NAME }}
          build-number: ${{ github.event.inputs.BUILD_NUMBER }}
          release-note: ${{ github.event.inputs.RELEASE_NOTE }}

      ## For uploading to GitHub Release.
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-aab
          path: ./build/release.aab

  ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          # SSH private key used to access your Fastlane match repository.
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Flutter SDK Cache
        uses: actions/cache@v3
        with:
          path: /Users/runner/hostedtoolcache/flutter
          key: ${{ runner.os }}-flutter-${{ vars.FLUTTER_VERSION }}

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: ${{ vars.FLUTTER_VERSION }}

      - name: Build & Deploy
        uses: MTtankkeo/flutter-fastlane-action@main
        with:
          platform: ios
          version-name: ${{ github.event.inputs.VERSION_NAME }}
          build-number: ${{ github.event.inputs.BUILD_NUMBER }}
          release-note: ${{ github.event.inputs.RELEASE_NOTE }}
          match-repository: Grimity/grimity-flutter-certs
          match-password: ${{ secrets.MATCH_PASSWORD }}
          appstore-connect-issuer-id: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          appstore-connect-key-id: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
          appstore-connect-key: ${{ secrets.APP_STORE_CONNECT_KEY }}
          appstore-team-id: ${{ secrets.APP_STORE_TEAM_ID }}

      ## For uploading to GitHub Release.
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: ./build/release.ipa

  # This job uploads artifacts to a GitHub release, but it is optional.
  # Remove this job if you do not want it.
  release:
    runs-on: ubuntu-latest
    needs: [android, ios]
    permissions:
      contents: write # Required for push and release operations
      packages: write
    steps:
      - name: Download Artifact (Android)
        uses: actions/download-artifact@v4
        with:
          name: android-aab
          path: ./build

      - name: Download Artifact (iOS)
        uses: actions/download-artifact@v4
        with:
          name: ios-ipa
          path: ./build

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./build/release.aab
            ./build/release.ipa
          tag_name: v${{ github.event.inputs.VERSION_NAME }}
          name: "v${{ github.event.inputs.VERSION_NAME }} (Build ${{ github.event.inputs.BUILD_NUMBER }})"
          body: |
            ## Deployment Information
            > This build was checked out and deployed from [${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }}).

            | Item | Value |
            | --- | --- |
            | **Build Version** | ${{ github.event.inputs.VERSION_NAME }} |
            | **Build Number** | ${{ github.event.inputs.BUILD_NUMBER }} |
            | **Release Notes** | ${{ github.event.inputs.RELEASE_NOTE }} |
            | **Commit SHA** | ${{ github.sha }} |
            | **Flutter Version** | ${{ vars.FLUTTER_VERSION }} |

            ## Target Files
            - Android App Bundle: `release.aab`
            - iOS IPA: `release.ipa`

            > [!WARNING]
            > These build files were automatically uploaded by the workflow.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
